export const students = {
  studentApplicants: {
    asdawqweqwfq: {
      id: 1,
      firstName: "Edwin",
      lastName: "Agbenyega",
      otherNames: "Dela Kwesi Mensah",
      address: "Somewhere only we know",
      dateOfBirth: "12/08/1991",
      gender: "Male",
      hometown: "Tsyome Sabadu",
      nationality: "Ghanaian",
      religiousAffiliation: "Christian",
      formerSchool: "University of New Mexico",
      disabilityStatus: "Not Disabled",
      disabilityInfo: "",
      createdAt: "06/29/2020",
      updatedAt: null,
      createdBy: "Edwin Agbenyega",
      updatedBy: null,
    }
  },
  studentList: {
    mlanglois: {
      id: 1,
      uid: "mlanglois",
      firstName: "Mariele",
      lastName: "L' Anglois",
      gender: "Female",
      grade: "n1",
      tuitionOwed: 250,
    },
    lkenset: {
      id: 2,
      uid: "lkenset",
      firstName: "Lucais",
      lastName: "Kenset",
      gender: "Male",
      grade: "n2",
      tuitionOwed: 250,
    },
    ekollach: {
      id: 3,
      uid: "ekollach",
      firstName: "Elbert",
      lastName: "Kollach",
      gender: "Male",
      grade: "kg1",
      tuitionOwed: 250,
    },
    dcastiglio: {
      id: 4,
      uid: "dcastiglio",
      firstName: "Dallon",
      lastName: "Castiglio",
      gender: "Male",
      grade: "kg2",
      tuitionOwed: 250,
    },
    forneles: {
      id: 5,
      uid: "forneles",
      firstName: "Fay",
      lastName: "Orneles",
      gender: "Female",
      grade: "p1",
      tuitionOwed: 250,
    },
    afeeham: {
      id: 6,
      uid: "afeeham",
      firstName: "Abe",
      lastName: "Feeham",
      gender: "Male",
      grade: "p2",
      tuitionOwed: 250,
    },
    jginnally: {
      id: 7,
      uid: "jginnally",
      firstName: "Josephina",
      lastName: "Ginnally",
      gender: "Female",
      grade: "p3",
      tuitionOwed: 250,
    },
    bnials: {
      id: 8,
      uid: "bnials",
      firstName: "Bordy",
      lastName: "Nials",
      gender: "Male",
      grade: "p3",
      tuitionOwed: 250,
    },
    warnauduc: {
      id: 9,
      uid: "warnauduc",
      firstName: "Ward",
      lastName: "Arnauduc",
      gender: "Male",
      grade: "p1",
      tuitionOwed: 250,
    },
    glonghi: {
      id: 10,
      uid: "glonghi",
      firstName: "Gregoire",
      lastName: "Longhi",
      gender: "Male",
      grade: "p2",
      tuitionOwed: 250,
    },
  }
}