export const StudentActionTypes = {
  ADD_STUDENT: 'ADD_STUDENT',
  ADD_STUDENT_APPLICANT: 'ADD_STUDENT_APPLICANT',
  DELETE_STUDENT_APPLICANT: 'DELETE_STUDENT_APPLICANT',
  GET_STUDENTS: 'GET_STUDENTS',
  UPDATE_STUDENT: 'UPDATE_STUDENTS',
  UPDATE_STUDENT_TUITION_OWED: 'UPDATE_STUDENT_TUITION_OWED'
}
